import Axios from 'axios'
import NavAdmin from '@/components/NavAdmin'
import ProfessionalAction from '@/components/ProfessionalAction'  // Ajuste o nome do componente de ação
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import MenuUsers from '@/components/MenuUsers'

export default function idProfissional() {

  const API_URL = "http://localhost:8080/api/profissionais"  // URL de profissionais
  
  const [profissionais, setProfissionais] = useState([]); 
  
  useEffect(() => {
    const getAllProfissionais = async () => {
      try {
        const response = await Axios.get(API_URL);
        setProfissionais(response.data);
        console.log(response.data);
      } catch (error) {
        console.error('Erro ao buscar os profissionais:', error);
      }
    };

    getAllProfissionais();

  }, []);

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuUsers />
      </div>

      <div className="d-flex justify-content-center p-2">
        <div className="container">
          <div className="row border-bottom">
            <h3> Lista de Profissionais </h3>
          </div>

          <div className="p-3 text-center container">
            <Link className="nav-link" href="/admin/profissionais/create">
              <button className="btn btn-primary btn-lg w-50 p-2">Cadastrar</button>
            </Link>
          </div>
          <div className="row">
            {profissionais.map(profissional => (
              <div key={profissional.idProfissionais} className="col-md-4 mb-3" id={`profissional-${profissional.idProfissionais}`}>
                <div className="card" data-id={profissional.idProfissionais}>
                  <div className="card-body">
                    <h5 className="card-title">{profissional.primeiroNome} {profissional.ultimoNome}</h5>
                    <p className="card-text"><strong>Pedagogo?:</strong> {profissional.pedagogo === 1 ? 'Sim' : 'Não'}</p>
                    <p className="card-text"><strong>Profissao:</strong> {profissional.profissao}</p>
                    <p className="card-text"><strong>Descricao:</strong> {profissional.descricao}</p>
                    <div className="card-text">
                      <strong>Horários:</strong>
                      <ul>
                        {profissional.horarios.split(";").map((horario, index) => (
                          <li key={index}>{horario.trim()}</li>
                        ))}
                      </ul>
                    </div>
                  <div>
                      <ProfessionalAction pid={profissional.idProfissionais}></ProfessionalAction> {/* Alterar componente de ação para "PatientAction" */}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>  
    </>
  )
}
